### ISSUE TITLE
inferno alias doesn't work when creating new project

### ISSUE THREAD

**Issue by rafaelkallis** [infernojs/brunch-with-inferno#1]
Creating an inferno project using `brunch new -s inferno` doesn't work atm even though it is registered in the [skeleton list](https://github.com/brunch/skeletons/blob/master/skeletons.json) of brunch. 

Note that you can still use `brunch new -s infernojs/brunch-with-inferno` to create a new inferno project.

An [issue](https://github.com/brunch/brunch/issues/1623) has been opened on the main brunch repository.

**Comment by paulmillr** [comment]
Should have been fixed.

**Comment by rafaelkallis** [comment]
Thanks a lot @paulmillr
`brunch new -s inferno` seems to be working for brunch `v2.10.0`
