### ISSUE TITLE
Hydration error since Inferno@v1.2.0

### ISSUE THREAD

**Issue by rafaelkallis** [infernojs/brunch-with-inferno#2]
Since the latest inferno update `v1.2.0`, a new error gets logged in the console while using brunch.

`Inferno hydration: Server-side markup doesn't match client-side markup`.

Can confirm that in inferno `v1.1.2` this error doesn't show up.

Steps to recreate the observation: 

Set dependencies in `package.json`:
```
"dependencies": {
    "inferno": "1.2.0",
    "inferno-component": "1.2.0"
}
```

The observation doesn't happen when `package.json` is as follows:
```
"dependencies": {
    "inferno": "1.1.2",
    "inferno-component": "1.1.2"
}
```

Will investigate further in the next days.

**Comment by rafaelkallis** [comment]
Possibly linked to [this issue](https://github.com/infernojs/inferno/issues/687).

**Comment by trueadm** [comment]
@rafaelkallis are you using SSR? What element are you rendering to as well?

**Comment by rafaelkallis** [comment]
@trueadm in order to properly recreate this issue you have to launch a new brunch based inferno project. Nothing simpler than `mkdir test && cd test && npm install brunch -g && brunch new -s inferno && npm start` then head over to your browser `http://localhost:3333`. For code you can just head over to `app/initialize.js`, you can pick it up from there.

No SSR rendering used as far as I can tell, except if there's some brunch magic behind the scenes which I'm not aware of. `inferno-server` isn't installed either.

**Comment by trueadm** [comment]
@rafaelkallis are you `Inferno.render` rendering to a DOM node that already has content in it?

**Comment by rafaelkallis** [comment]
@trueadm no.

Here's the relevant snippet from `index.html`:
```
<div id="app"></div>
```

And here's the `Inferno.render` part:
```
Inferno.render( (<div></div>), document.getElementById('app'));
```

EDIT: I also would like to point out that even though the error gets fired, the elements get rendered correctly.

**Comment by trueadm** [comment]
This sounds like a bug on Inferno, maybe we can move this issue to the main repo and try and reproduce outside of brunch to verify?

**Comment by edgesoft** [comment]
@rafaelkallis @trueadm Have the same issue with Brunch. If you build the create-inferno-app it will not run at all, but it will run in dev.

**Comment by Havunen** [comment]
This happens because index.html has white space in html tag <div id="app">

its written like this:

```
<div id="app">
</div>
```

It should be like you posted above:
```
<div id="app"></div>
```

**Comment by Havunen** [comment]
This is not error: Its warning about incorrect html

**Comment by edgesoft** [comment]
@Havunen Hummm not sure. Because when it's compiled the app stops working.

**Comment by trueadm** [comment]
@edgesoft The whitespace between the opening and closing tags means that there is a `TextNode` as the `firstChild`, which is a diff error with hydration. Inferno never used to warn on this, but it appears that is throwing an error in production now? I've not looked into it (not had time today) but it sounds like there's something broken with the warning system.

**Comment by Havunen** [comment]
It does nothing for production (not even validation):
https://github.com/infernojs/inferno/blob/dev/src/DOM/hydration.ts#L116-L120

The function itselfs just logs error to console, doesn't throw
https://github.com/infernojs/inferno/blob/dev/src/shared.ts#L72-L74

**Comment by trueadm** [comment]
@Havunen Sounds like an issue with brunch then? I just tested quickly and this error message isn't breaking a prod build for me when I hydrate on bad content.

**Comment by rafaelkallis** [comment]
@Havunen seems that was it.

Closing this issue for now.
