### ISSUE TITLE
Modules besides "inferno" and "inferno-component" not found

### ISSUE THREAD

**Issue by rafaelkallis** [infernojs/brunch-with-inferno#3]
It seems that all inferno packages except `inferno` and `inferno-component` suffer under this issue. When adding an inferno package such as `inferno-redux` or `inferno-router`, and while importing it in your code `import { Provider } from 'inferno-redux'`, we get the following error in the console:

```
Error: Cannot find module 'redux' from 'inferno/dist/inferno-redux.node.js'
```

By now I can confirm this happens with `inferno-redux` and `inferno-router`.

Will investigate further in the next days.

**Comment by rafaelkallis** [comment]
Another observation:

On packages where this error happens, they are not required by relative paths.

For example:

[inferno-component.js](https://github.com/infernojs/inferno/blob/master/packages/inferno-component/inferno-component.js) requires with a relative path

```
module.exports = require('./../inferno/dist/inferno-component.node');
```

In contrast to [inferno-redux.js](https://github.com/infernojs/inferno/blob/master/packages/inferno-redux/inferno-redux.js) and [inferno-router.js](https://github.com/infernojs/inferno/blob/master/packages/inferno-router/inferno-router.js), which do not require by relative path.
```
module.exports = require('inferno/dist/inferno-redux.node');
```
```
module.exports = require('inferno/dist/inferno-router.node');
```


(EDIT: meant *relative* path, not absolute. Changed)

**Comment by trueadm** [comment]
This sounds like an Inferno bug on the main repo, maybe related to this line?

https://github.com/infernojs/inferno/blob/master/config/rollup.config.js#L77

@lukeed might know more as he was the one who recently suggested changes on this?

**Comment by rafaelkallis** [comment]
quick update:

`inferno-redux` seems to be working after importing both `{ createStore }` from `redux` and `createElement` from `inferno-create-element`.

```
import { Provider } from 'inferno-redux';
import { createStore } from 'redux';
import createElement from 'inferno-create-element';
```

**Comment by rafaelkallis** [comment]
update regarding `inferno-router`:

`inferno-router` seems to be working after importing `createElement` from `inferno-create-element`.

```
import { Router, Route, IndexRoute } from 'inferno-router';
import createElement from 'inferno-create-element';
```

**Comment by rafaelkallis** [comment]
**update:** it seems that the error has vanished for both `inferno-redux` and `inferno-router`, even when not importing `createElement`. I'm closing this for now.
