### ISSUE TITLE
Auto reload module not working

### ISSUE THREAD

**Issue by dengunya** [infernojs/brunch-with-inferno#5]
For some reason browser does not reload after source was changed.
Seems it should work without any additional settings.
There's "auto-reload-brunch": "^2.7.1" in devDependencies.
Other skeletons work fine, can't figuree out what's the problem here...

**Comment by rafaelkallis** [comment]
Is your client machine the same as the server machine?

**Comment by dengunya** [comment]
@rafaelkallis yes. I just trying to set up dev environment localy.

**Comment by rafaelkallis** [comment]
I recently updated the dependencies. Do you mind trying out with the updated skeleton and let me know if you still get the same results? Thank you.

**Comment by rafaelkallis** [comment]
ping @dengunya

**Comment by dengunya** [comment]
@rafaelkallis sorry, didn't work.
Inferno-component is deprecated now, so you removed it. So we should extend _Inferno.Component_, not _Component_ now. That's a new issue I guess. I have an error in browser console. Did you try to run it ? Anyway auto-reload still doesn't work so we should figure out what's wrong

**Comment by rafaelkallis** [comment]
@dengunya 
I finally believe I found what was causing the issue. In the brunch config I changed the "entryPoint" key under javascript to "joinTo". Please go ahead and give the newly pushed changes a try, I'm certain it should work now. Also note Inferno has been updated to version 5.

**Comment by rafaelkallis** [comment]
I assume the bug is fixed. Reopen issue otherwise.
